# python_exception_hook